In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('modified_data_v1.csv')

In [3]:
pd.set_option("display.max_columns", None)

In [4]:
df.head()

shop_id  shop_area_sq_ft shop_profile  quantity_sold    total  customer_id  \
0  SHOP047              528     Moderate           1692   842960          928   
1  SHOP009              676         High           4589  1970870         2498   
2  SHOP083              676          Low           3614  1691985         1900   
3  SHOP117              676          Low           4074  2325980         2037   
4  SHOP042              676          Low           3272  1340215         1841   

   BOTTLED DRINKING WATER 1.5L  BOTTLED DRINKING WATER 500ML  \
0                           42                           124   
1                          123                           427   
2                           81                           256   
3                          116                           152   
4                           91                           228   

   CHOCOLATE MILK 180ML  CREAM SODA 1.5L  CREAM SODA 1L  CREAM SODA 500ML  \
0                     0              249             28               278   
1                     0              686             62               451   
2                     3              592             76               408   
3                     0              565             58               343   
4                     0              478             40               385   

   CREAM SODA APPLE POP 1L  DRY GINGER ALE PET 500ML  FIT O MANGO 1L  \
0                       71                         8              66   
1                      203                        56              76   
2                      186                        67              93   
3                      318                       155             115   
4                      138                        74              98   

   FIT O MANGO 200ML  FIT O MIXED FRUIT 1L  FIT O MIXED FRUIT 200ML  \
0                 87                    31                       44   
1                102                   115                      182   
2                 89                    95                       92   
3                166                   110                      188   
4                 66                    67                       53   

   FIT O ORANGE 1L  FIT O ORANGE 200ML  GINGER BEER 1.5L  GINGER BEER 1L  \
0               66                 137               306             189   
1              208                 223              1018             552   
2              211                 172               734             559   
3              216                 150               797             468   
4              183                 142               666             467   

   GINGER BEER 400ML  GINGER BEER 500ML  GINGER BEER SUGAR FREE 500ML  \
0                 51                 84                            26   
1                 69                254                            96   
2                 29                122                            67   
3                 56                 81                            85   
4                 47                147                            68   

   KIK COLA 1L  LEMONADE 1.5L  LEMONADE 1L  LEMONADE 500ML  \
0            7             41           19              31   
1           30            194           15             113   
2           43            168           15              63   
3           72            182           30              57   
4           25            131           34              57   

   LIME CRUSH JUICE 1L  NECTO 1.5L  NECTO 1L  NECTO 500ML  ORANGE BARLEY 1.5L  \
0                    0         102         6           25                 113   
1                    0         338        24           79                 333   
2                    0         286        29           40                 359   
3                    0         402        10           45                 339   
4                    0         178         7           26                 265   

   ORANGE CRUSH 1.5L  ORANGE CRUSH 1L  ORANGE CRUSH 

In [5]:
df.iloc[100:].head()

shop_id  shop_area_sq_ft shop_profile  quantity_sold    total  \
100  SHOP046              545          NaN           3438  2607865   
101  SHOP024              676          NaN           2883  1308795   
102  SHOP023              617          NaN           4103  2570425   
103  SHOP097              310          NaN           3148  2642380   
104  SHOP044              715          NaN           2641  1310440   

     customer_id  BOTTLED DRINKING WATER 1.5L  BOTTLED DRINKING WATER 500ML  \
100         1736                          294                           742   
101         1641                          224                           264   
102         2227                          118                           189   
103         1669                          189                           314   
104         1552                           72                            21   

     CHOCOLATE MILK 180ML  CREAM SODA 1.5L  CREAM SODA 1L  CREAM SODA 500ML  \
100                     0              688             49               351   
101                     0              516             50               390   
102                     2              982             63               571   
103                     0              301              0               296   
104                     0              365             20               277   

     CREAM SODA APPLE POP 1L  DRY GINGER ALE PET 500ML  FIT O MANGO 1L  \
100                      124                        51              64   
101                       73                        72              76   
102                      169                       101              94   
103                       97                       225              87   
104                       64                       137              41   

     FIT O MANGO 200ML  FIT O MIXED FRUIT 1L  FIT O MIXED FRUIT 200ML  \
100                 85                   105                      112   
101                 66                    70                      112   
102                169                   100                      274   
103                105                    83                      128   
104                 77                    54                       79   

     FIT O ORANGE 1L  FIT O ORANGE 200ML  GINGER BEER 1.5L  GINGER BEER 1L  \
100              193                 112               673             234   
101              141                  76               568             194   
102              165                 106               893             273   
103              317                 129               669               0   
104              101                  66               544             210   

     GINGER BEER 400ML  GINGER BEER 500ML  GINGER BEER SUGAR FREE 500ML  \
100                 51                105                            69   
101                 81                126                           103   
102                 11                138                           107   
103                 32                228                           121   
104                 26                101                            42   

     KIK COLA 1L  LEMONADE 1.5L  LEMONADE 1L  LEMONADE 500ML  \
100           28            105           15              69   
101           18             73           12              29   
102           27            203           62              22   
103           12            210           34              84   
104           28             66           28              47   

     LIME CRUSH JUICE 1L  NECTO 1.5L  NECTO 1L  NECTO 500ML  \
100                    0         460        30           38   
101                    0         330        14           34   
102                    0         391        34           36   
103                    0         215         0           46   
104                    0         149        25           41   

     ORANGE BARLEY 1.5L  ORANGE CRUSH 1.5L  ORANGE CRUSH 1L  \
100

In [6]:
train = df.iloc[:100].copy()
test = df.iloc[100:].copy()

In [7]:
train = train.drop(columns=['shop_id'])

In [8]:
test = test.drop(columns=['shop_id'])

In [9]:
train['shop_profile'] = train['shop_profile'].replace({'High':2, 'Moderate':1, 'Low':0})

In [10]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 42 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   shop_area_sq_ft               100 non-null    int64
 1   shop_profile                  100 non-null    int64
 2   quantity_sold                 100 non-null    int64
 3   total                         100 non-null    int64
 4   customer_id                   100 non-null    int64
 5   BOTTLED DRINKING WATER 1.5L   100 non-null    int64
 6   BOTTLED DRINKING WATER 500ML  100 non-null    int64
 7   CHOCOLATE MILK 180ML          100 non-null    int64
 8   CREAM SODA 1.5L               100 non-null    int64
 9   CREAM SODA 1L                 100 non-null    int64
 10  CREAM SODA 500ML              100 non-null    int64
 11  CREAM SODA APPLE POP 1L       100 non-null    int64
 12  DRY GINGER ALE PET 500ML      100 non-null    int64
 13  FIT O MANGO 1L                100 no

In [11]:
X = train.drop(columns=['shop_profile']).values
Y = train['shop_profile'].values

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42, stratify=Y)

In [12]:
from catboost import CatBoostClassifier
model = CatBoostClassifier(
    iterations=1000,
    random_seed=0,
    learning_rate=0.01
)
model.fit(
    x_train, y_train,
#     cat_features=cat_cols,
#     eval_set=(X_val, y_val),
#     logging_level='Silent'
)
print('Model is fitted: ' + str(model.is_fitted()))
print('Model params:')
print(model.get_params())

0:	learn: 1.0962593	total: 144ms	remaining: 2m 23s
1:	learn: 1.0928252	total: 146ms	remaining: 1m 12s
2:	learn: 1.0896281	total: 148ms	remaining: 49.2s
3:	learn: 1.0854972	total: 150ms	remaining: 37.3s
4:	learn: 1.0833696	total: 152ms	remaining: 30.3s
5:	learn: 1.0794785	total: 154ms	remaining: 25.5s
6:	learn: 1.0770592	total: 156ms	remaining: 22.1s
7:	learn: 1.0739922	total: 157ms	remaining: 19.5s
8:	learn: 1.0710070	total: 160ms	remaining: 17.6s
9:	learn: 1.0679198	total: 162ms	remaining: 16s
10:	learn: 1.0645297	total: 163ms	remaining: 14.7s
11:	learn: 1.0619218	total: 165ms	remaining: 13.6s
12:	learn: 1.0600617	total: 167ms	remaining: 12.7s
13:	learn: 1.0581106	total: 169ms	remaining: 11.9s
14:	learn: 1.0553239	total: 171ms	remaining: 11.2s
15:	learn: 1.0529980	total: 173ms	remaining: 10.6s
16:	learn: 1.0505929	total: 175ms	remaining: 10.1s
17:	learn: 1.0481163	total: 177ms	remaining: 9.66s
18:	learn: 1.0460077	total: 179ms	remaining: 9.23s
19:	learn: 1.0437014	total: 181ms	remaini

205:	learn: 0.7051960	total: 526ms	remaining: 2.03s
206:	learn: 0.7040412	total: 529ms	remaining: 2.03s
207:	learn: 0.7032023	total: 531ms	remaining: 2.02s
208:	learn: 0.7013225	total: 533ms	remaining: 2.02s
209:	learn: 0.6997393	total: 535ms	remaining: 2.01s
210:	learn: 0.6990774	total: 537ms	remaining: 2.01s
211:	learn: 0.6972095	total: 539ms	remaining: 2s
212:	learn: 0.6961277	total: 541ms	remaining: 2s
213:	learn: 0.6952106	total: 543ms	remaining: 2s
214:	learn: 0.6940074	total: 545ms	remaining: 1.99s
215:	learn: 0.6929824	total: 548ms	remaining: 1.99s
216:	learn: 0.6919678	total: 549ms	remaining: 1.98s
217:	learn: 0.6908829	total: 551ms	remaining: 1.98s
218:	learn: 0.6899252	total: 553ms	remaining: 1.97s
219:	learn: 0.6887788	total: 555ms	remaining: 1.97s
220:	learn: 0.6876743	total: 557ms	remaining: 1.96s
221:	learn: 0.6865213	total: 560ms	remaining: 1.96s
222:	learn: 0.6855714	total: 562ms	remaining: 1.96s
223:	learn: 0.6846272	total: 564ms	remaining: 1.95s
224:	learn: 0.6830472

410:	learn: 0.4975515	total: 911ms	remaining: 1.3s
411:	learn: 0.4969900	total: 912ms	remaining: 1.3s
412:	learn: 0.4962921	total: 915ms	remaining: 1.3s
413:	learn: 0.4948517	total: 917ms	remaining: 1.3s
414:	learn: 0.4939548	total: 918ms	remaining: 1.29s
415:	learn: 0.4930829	total: 920ms	remaining: 1.29s
416:	learn: 0.4922966	total: 923ms	remaining: 1.29s
417:	learn: 0.4910932	total: 925ms	remaining: 1.29s
418:	learn: 0.4901188	total: 927ms	remaining: 1.28s
419:	learn: 0.4891586	total: 929ms	remaining: 1.28s
420:	learn: 0.4884434	total: 931ms	remaining: 1.28s
421:	learn: 0.4876081	total: 933ms	remaining: 1.28s
422:	learn: 0.4866134	total: 935ms	remaining: 1.27s
423:	learn: 0.4858710	total: 937ms	remaining: 1.27s
424:	learn: 0.4846186	total: 939ms	remaining: 1.27s
425:	learn: 0.4839948	total: 941ms	remaining: 1.27s
426:	learn: 0.4833896	total: 943ms	remaining: 1.26s
427:	learn: 0.4825949	total: 945ms	remaining: 1.26s
428:	learn: 0.4819263	total: 947ms	remaining: 1.26s
429:	learn: 0.48

607:	learn: 0.3569597	total: 1.29s	remaining: 834ms
608:	learn: 0.3563040	total: 1.29s	remaining: 831ms
609:	learn: 0.3557056	total: 1.3s	remaining: 829ms
610:	learn: 0.3551392	total: 1.3s	remaining: 827ms
611:	learn: 0.3544660	total: 1.3s	remaining: 825ms
612:	learn: 0.3537602	total: 1.3s	remaining: 822ms
613:	learn: 0.3530934	total: 1.3s	remaining: 820ms
614:	learn: 0.3524709	total: 1.31s	remaining: 818ms
615:	learn: 0.3519138	total: 1.31s	remaining: 816ms
616:	learn: 0.3510119	total: 1.31s	remaining: 814ms
617:	learn: 0.3504426	total: 1.31s	remaining: 811ms
618:	learn: 0.3497100	total: 1.31s	remaining: 809ms
619:	learn: 0.3490403	total: 1.32s	remaining: 807ms
620:	learn: 0.3485427	total: 1.32s	remaining: 805ms
621:	learn: 0.3479209	total: 1.32s	remaining: 803ms
622:	learn: 0.3473552	total: 1.32s	remaining: 801ms
623:	learn: 0.3467662	total: 1.32s	remaining: 798ms
624:	learn: 0.3460493	total: 1.33s	remaining: 796ms
625:	learn: 0.3453639	total: 1.33s	remaining: 794ms
626:	learn: 0.344

811:	learn: 0.2514687	total: 1.68s	remaining: 388ms
812:	learn: 0.2511597	total: 1.68s	remaining: 386ms
813:	learn: 0.2507560	total: 1.68s	remaining: 384ms
814:	learn: 0.2502972	total: 1.68s	remaining: 382ms
815:	learn: 0.2497969	total: 1.68s	remaining: 380ms
816:	learn: 0.2492230	total: 1.69s	remaining: 378ms
817:	learn: 0.2488113	total: 1.69s	remaining: 376ms
818:	learn: 0.2484326	total: 1.69s	remaining: 374ms
819:	learn: 0.2480444	total: 1.69s	remaining: 371ms
820:	learn: 0.2474666	total: 1.69s	remaining: 369ms
821:	learn: 0.2470587	total: 1.7s	remaining: 367ms
822:	learn: 0.2466263	total: 1.7s	remaining: 365ms
823:	learn: 0.2463083	total: 1.7s	remaining: 363ms
824:	learn: 0.2458133	total: 1.7s	remaining: 361ms
825:	learn: 0.2453800	total: 1.7s	remaining: 359ms
826:	learn: 0.2449745	total: 1.7s	remaining: 357ms
827:	learn: 0.2446215	total: 1.71s	remaining: 354ms
828:	learn: 0.2441665	total: 1.71s	remaining: 352ms
829:	learn: 0.2437864	total: 1.71s	remaining: 350ms
830:	learn: 0.2431

In [13]:
pred = model.predict(x_test)

In [14]:
prediction = pd.DataFrame()
prediction['Actual'] = y_test
prediction['Presicted'] = pred
prediction

Actual  Presicted
0        1          2
1        2          2
2        1          0
3        2          2
4        0          0
5        1          2
6        0          0
7        2          2
8        0          0
9        0          0
10       0          0
11       2          2
12       0          0
13       1          0
14       0          1
15       1          1
16       2          1
17       1          0
18       2          2
19       1          2

In [15]:
from sklearn.metrics import f1_score

f1_score(y_test, pred, average='micro')

0.6

In [16]:
cols= train.drop(columns=['shop_profile']).columns

In [17]:
pd.DataFrame({'names':cols, 'import':model.feature_importances_}).sort_values(by='import', ascending=False)

names     import
5   BOTTLED DRINKING WATER 500ML  12.486059
28                    NECTO 1.5L   4.461425
4    BOTTLED DRINKING WATER 1.5L   4.369894
38         STRAWBERRY MILK 180ML   4.299995
32             ORANGE CRUSH 1.5L   4.252107
30                   NECTO 500ML   3.434933
10       CREAM SODA APPLE POP 1L   3.247246
9               CREAM SODA 500ML   3.222091
0                shop_area_sq_ft   3.219646
33               ORANGE CRUSH 1L   3.125661
26                LEMONADE 500ML   2.873609
3                    customer_id   2.819644
37                 SODA PET 1.5L   2.732262
11      DRY GINGER ALE PET 500ML   2.560034
7                CREAM SODA 1.5L   2.539706
36                    SODA 500ML   2.479902
19                GINGER BEER 1L   2.405489
39               TONIC PET 500ML   2.355331
22  GINGER BEER SUGAR FREE 500ML   2.018270
1                  quantity_sold   1.903287
23                   KIK COLA 1L   1.853420
34            ORANGE CRUSH 500ML   1.829509
15       FIT O MIXED FRUIT 200ML   1.742706
40              TWISTEE APPLE 1L   1.702034
20             GINGER BEER 400ML   1.700329
2                          total   1.695808
35                       SODA 1L   1.665269
21             GINGER BEER 500ML   1.604892
29                      NECTO 1L   1.596274
16               FIT O ORANGE 1L   1.578651
24                 LEMONADE 1.5L   1.546569
12                FIT O MANGO 1L   1.520511
8                  CREAM SODA 1L   1.454602
31            ORANGE BARLEY 1.5L   1.255163
14          FIT O MIXED FRUIT 1L   1.187710
13             FIT O MANGO 200ML   1.175953
17            FIT O ORANGE 200ML   1.171581
18              GINGER BEER 1.5L   1.168789
25                   LEMONADE 1L   1.053587
6           CHOCOLATE MILK 180ML   0.678921
27           LIME CRUSH JUICE 1L   0.011131

In [18]:
from MLmodels import MachineLearningModels
MachineLearningModels.ml_model(x_train, y_train, x_test, y_test)

Logistic Regression: 

[0.5    0.5625 0.75   0.5    0.5   ]
Accuracy: 56.25 %

Classification Report:
              precision    recall  f1-score   support

           0       0.55      0.86      0.67         7
           1       0.25      0.14      0.18         7
           2       0.40      0.33      0.36         6

    accuracy                           0.45        20
   macro avg       0.40      0.44      0.40        20
weighted avg       0.40      0.45      0.41        20


Confusion Matrix:
[[6 1 0]
 [3 1 3]
 [2 2 2]]
---------------------------------------------------------------------------------------
Gaussian Naive Bayes: 

[0.375  0.625  0.5625 0.625  0.375 ]
Accuracy: 51.25 %

Classification Report:
              precision    recall  f1-score   support

           0       0.56      0.71      0.63         7
           1       0.50      0.29      0.36         7
           2       0.71      0.83      0.77         6

    accuracy                           0.60        20
   macr

C:\Users\vipoo\anaconda3\envs\tf\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\vipoo\anaconda3\envs\tf\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\vipoo\anaconda3\envs\tf\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[0.4375 0.6875 0.625  0.5625 0.5625]
Accuracy: 57.50 %

Classification Report:
              precision    recall  f1-score   support

           0       0.62      0.71      0.67         7
           1       0.40      0.29      0.33         7
           2       0.71      0.83      0.77         6

    accuracy                           0.60        20
   macro avg       0.58      0.61      0.59        20
weighted avg       0.57      0.60      0.58        20


Confusion Matrix:
[[5 2 0]
 [3 2 2]
 [0 1 5]]
---------------------------------------------------------------------------------------
Ada Boost Classifier: 

[0.4375 0.8125 0.4375 0.625  0.375 ]
Accuracy: 53.75 %

Classification Report:
              precision    recall  f1-score   support

           0       0.45      0.71      0.56         7
           1       0.25      0.14      0.18         7
           2       0.60      0.50      0.55         6

    accuracy                           0.45        20
   macro avg       0.43      0

In [19]:
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

XGB = LGBMClassifier()
XGB.fit(x_train, y_train)
pred_xgb = XGB.predict(x_test)

In [20]:
prediction = pd.DataFrame()
prediction['Actual'] = y_test
prediction['Presicted'] = pred_xgb
prediction

Actual  Presicted
0        1          2
1        2          2
2        1          1
3        2          2
4        0          0
5        1          2
6        0          0
7        2          2
8        0          0
9        0          0
10       0          0
11       2          2
12       0          0
13       1          1
14       0          1
15       1          1
16       2          1
17       1          1
18       2          2
19       1          2

In [21]:
prediction.Presicted.value_counts()

2    8
1    6
0    6
Name: Presicted, dtype: int64

In [22]:
from sklearn.metrics import f1_score

f1_score(y_test, pred_xgb, average='micro')

0.75

In [37]:
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

# XGB = XGBClassifier()
XGB = LGBMClassifier()
XGB.fit(X, Y)
pred_test_xgb = XGB.predict(test.drop(columns=['shop_profile']).values)

In [38]:
pred_test_xgb

array([2, 0, 0, 1, 1, 2, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 2, 2, 1, 0, 0,
       2, 0], dtype=int64)

In [39]:
df_test = pd.read_csv('Testing-data.csv')

In [40]:
df_test.shop_profile = pred_test_xgb
df_test.shop_profile = df_test.shop_profile.replace({2:'High', 1:'Moderate', 0:'Low'})

In [41]:
df_test

shop_id shop_profile
0   SHOP046         High
1   SHOP024          Low
2   SHOP023          Low
3   SHOP097     Moderate
4   SHOP044     Moderate
5   SHOP030         High
6   SHOP038     Moderate
7   SHOP029     Moderate
8   SHOP096          Low
9   SHOP092     Moderate
10  SHOP081     Moderate
11  SHOP076          Low
12  SHOP080          Low
13  SHOP074          Low
14  SHOP107     Moderate
15  SHOP108          Low
16  SHOP019          Low
17  SHOP002         High
18  SHOP114         High
19  SHOP087     Moderate
20  SHOP050          Low
21  SHOP061          Low
22  SHOP056         High
23  SHOP070          Low

In [42]:
df_test.shop_profile.value_counts()

Low         11
Moderate     8
High         5
Name: shop_profile, dtype: int64

In [43]:
df_test.dtypes

shop_id         object
shop_profile    object
dtype: object

In [46]:
csv = 'submission1.csv'
df_test.to_csv(csv, index=False)

In [48]:
sub = pd.read_csv(csv)
sub.head()

shop_id shop_profile
0  SHOP046         High
1  SHOP024          Low
2  SHOP023          Low
3  SHOP097     Moderate
4  SHOP044     Moderate